import type { ConnectorConfig, ConnectorType } from './types'

export const CONNECTORS: Record<ConnectorType, ConnectorConfig> = {
  // ── Triggers ────────────────────────────────────────────────────────────────
  trigger: {
    type: 'trigger',
    label: 'Trigger',
    description: 'Start the workflow on an event, schedule, or webhook',
    color: '#818cf8',
    bgColor: '#1e1b4b',
    borderColor: '#3730a3',
    icon: '⚡',
    category: 'trigger',
    inputs: [
      {
        key: 'triggerType',
        label: 'Trigger Type',
        type: 'select',
        options: [
          { label: 'Manual (API call)', value: 'manual' },
          { label: 'Webhook (HTTP POST)', value: 'webhook' },
          { label: 'Quest Completed', value: 'questComplete' },
          { label: 'Objective Completed', value: 'objectiveCompleted' },
          { label: 'Quest Started', value: 'questStarted' },
          { label: 'Player at Location (GPS)', value: 'locationArrival' },
          { label: 'Egg Discovered', value: 'eggDiscovered' },
          { label: 'Monster Killed', value: 'monsterKilled' },
          { label: 'NFT Minted', value: 'nftMint' },
          { label: 'Token Balance Threshold', value: 'tokenBalance' },
          { label: 'Telegram Message', value: 'telegram' },
          { label: 'Cron Schedule', value: 'cron' },
          { label: 'A2A Message Received', value: 'a2aMessage' },
        ],
        required: true,
        default: 'manual',
      },
      { key: 'gameId', label: 'Game ID', type: 'text', placeholder: 'my-game (for quest triggers)' },
      { key: 'objectiveKey', label: 'Objective Key', type: 'text', placeholder: 'boss-defeated, level-complete' },
      { key: 'webhookPath', label: 'Webhook Path', type: 'text', placeholder: '/my-trigger' },
      { key: 'cronExpression', label: 'Cron Expression', type: 'text', placeholder: '0 9 * * * (daily 9am)' },
    ],
  },

  // ── Data & Storage ──────────────────────────────────────────────────────────
  holon: {
    type: 'holon',
    label: 'Holon',
    description: 'Read or write a holon — persist data cross-provider via HyperDrive',
    color: '#94a3b8',
    bgColor: '#0f172a',
    borderColor: '#334155',
    icon: '◎',
    category: 'data',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Load Holon', value: 'load' },
          { label: 'Save Holon', value: 'save' },
          { label: 'Search Holons', value: 'search' },
          { label: 'Load Children', value: 'loadChildren' },
          { label: 'Delete Holon', value: 'delete' },
        ],
        required: true,
        default: 'save',
      },
      { key: 'holonId', label: 'Holon ID', type: 'text', placeholder: '{{trigger.holonId}} or UUID' },
      { key: 'holonType', label: 'Holon Type', type: 'text', placeholder: 'QuestProof, NFT, Memory, GameState' },
      { key: 'metadata', label: 'Metadata (JSON)', type: 'textarea', placeholder: '{"key": "value"}' },
      {
        key: 'provider',
        label: 'Storage Provider',
        type: 'select',
        options: [
          { label: 'Auto (HyperDrive)', value: 'auto' },
          { label: 'MongoDB', value: 'MongoDBOASIS' },
          { label: 'Solana', value: 'SolanaOASIS' },
          { label: 'IPFS', value: 'IPFSOASIS' },
          { label: 'Holochain', value: 'HoloOASIS' },
        ],
        default: 'auto',
      },
    ],
  },
  nft: {
    type: 'nft',
    label: 'NFT',
    description: 'Mint, transfer, gate by ownership, or place as GeoNFT',
    color: '#fbbf24',
    bgColor: '#1c1400',
    borderColor: '#d97706',
    icon: '◈',
    category: 'data',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Mint NFT', value: 'mint' },
          { label: 'Transfer NFT', value: 'transfer' },
          { label: 'Check Ownership', value: 'checkOwnership' },
          { label: 'Place GeoNFT', value: 'placeGeo' },
          { label: 'Get NFTs for Avatar', value: 'getForAvatar' },
          { label: 'Create Monster NFT', value: 'createMonster' },
          { label: 'Deploy Boss NFT', value: 'deployBoss' },
        ],
        required: true,
        default: 'mint',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      { key: 'title', label: 'NFT Title', type: 'text', placeholder: 'Quest Reward NFT' },
      { key: 'symbol', label: 'Symbol', type: 'text', placeholder: 'QREWARD' },
      { key: 'description', label: 'Description', type: 'text', placeholder: 'Awarded for completing...' },
      { key: 'imageUrl', label: 'Image URL', type: 'text', placeholder: 'https://... or {{braid.imageUrl}}' },
      { key: 'nftId', label: 'NFT ID', type: 'text', placeholder: '{{step1.nftId}} (for transfer/check)' },
      { key: 'toWallet', label: 'Recipient Wallet', type: 'text', placeholder: '{{trigger.walletAddress}}' },
      {
        key: 'cluster',
        label: 'Cluster',
        type: 'select',
        options: [
          { label: 'Devnet (testing)', value: 'devnet' },
          { label: 'Mainnet', value: 'mainnet-beta' },
        ],
        default: 'devnet',
      },
    ],
  },
  world: {
    type: 'world',
    label: 'World',
    description: 'Create or update a game world / city state as a holon',
    color: '#22d3ee',
    bgColor: '#001a1f',
    borderColor: '#0891b2',
    icon: '◈',
    category: 'data',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Generate from Prompt', value: 'generateFromPrompt' },
          { label: 'Create World', value: 'create' },
          { label: 'Update State', value: 'updateState' },
          { label: 'Complete Quest in World', value: 'completeQuest' },
          { label: 'Get My Worlds', value: 'getMyWorlds' },
        ],
        required: true,
        default: 'generateFromPrompt',
      },
      { key: 'prompt', label: 'World Prompt', type: 'textarea', placeholder: 'A cyberpunk city on a water planet...' },
      { key: 'worldId', label: 'World ID', type: 'text', placeholder: 'For update/quest actions' },
      { key: 'questKey', label: 'Quest Key', type: 'text', placeholder: 'population_100 (for completeQuest)' },
      { key: 'stateJson', label: 'City State (JSON)', type: 'textarea', placeholder: '{"buildings": [...]}' },
    ],
  },
  webhook: {
    type: 'webhook',
    label: 'Webhook',
    description: 'Call any external HTTP API or notify a game client',
    color: '#94a3b8',
    bgColor: '#0d1117',
    borderColor: '#475569',
    icon: '↗',
    category: 'data',
    inputs: [
      {
        key: 'method',
        label: 'Method',
        type: 'select',
        options: [
          { label: 'POST', value: 'POST' },
          { label: 'GET', value: 'GET' },
          { label: 'PUT', value: 'PUT' },
          { label: 'DELETE', value: 'DELETE' },
        ],
        default: 'POST',
      },
      { key: 'url', label: 'URL', type: 'text', placeholder: 'https://api.example.com/endpoint', required: true },
      { key: 'headers', label: 'Headers (JSON)', type: 'textarea', placeholder: '{"Authorization": "Bearer {{env.JWT}}"}' },
      { key: 'body', label: 'Body (JSON)', type: 'textarea', placeholder: '{"success":true,"nftId":"{{step1.nftId}}"}' },
    ],
  },

  // ── AI & Agents ─────────────────────────────────────────────────────────────
  agent: {
    type: 'agent',
    label: 'Agent',
    description: 'Delegate a task to a registered A2A agent via SERV',
    color: '#a78bfa',
    bgColor: '#1e1030',
    borderColor: '#6d28d9',
    icon: '🤖',
    category: 'ai',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Send Task', value: 'sendTask' },
          { label: 'Discover Agents', value: 'discover' },
          { label: 'Send Payment Request (SERV)', value: 'servPayment' },
          { label: 'Execute AI Workflow', value: 'executeWorkflow' },
        ],
        required: true,
        default: 'sendTask',
      },
      { key: 'agentId', label: 'Agent ID', type: 'text', placeholder: 'Agent UUID or {{step1.agentId}}' },
      { key: 'serviceName', label: 'Service Name', type: 'text', placeholder: 'e.g. quest-narrator' },
      { key: 'task', label: 'Task Description', type: 'textarea', placeholder: 'Describe what the agent should do' },
      { key: 'servAmount', label: 'SERV Payment Amount', type: 'number', placeholder: '0.1' },
    ],
  },
  braid: {
    type: 'braid',
    label: 'BRAID',
    description: 'Run a bounded reasoning graph — generate quest narratives, evaluate conditions',
    color: '#f0abfc',
    bgColor: '#2d0a3e',
    borderColor: '#9333ea',
    icon: '🧠',
    category: 'ai',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Generate + Solve (Full)', value: 'full' },
          { label: 'Load Graph from Library', value: 'loadGraph' },
          { label: 'Solve with Existing Graph', value: 'solve' },
          { label: 'Save Graph to Library', value: 'saveGraph' },
        ],
        required: true,
        default: 'full',
      },
      { key: 'taskType', label: 'Task Type', type: 'text', placeholder: 'quest-narrative, location-lore, monster-description' },
      { key: 'inputs', label: 'Inputs (JSON)', type: 'textarea', placeholder: '{"location":"{{trigger.locationName}}","avatar":"{{trigger.avatarId}}"}' },
      { key: 'graphId', label: 'Graph Holon ID', type: 'text', placeholder: 'For solve or load actions' },
      {
        key: 'model',
        label: 'LLM Model',
        type: 'select',
        options: [
          { label: 'Anthropic (preferred)', value: 'anthropic' },
          { label: 'OpenAI', value: 'openai' },
        ],
        default: 'anthropic',
      },
    ],
  },

  // ── Financial ───────────────────────────────────────────────────────────────
  wallet: {
    type: 'wallet',
    label: 'Wallet',
    description: 'Send tokens, check balance, manage wallets',
    color: '#34d399',
    bgColor: '#001f14',
    borderColor: '#059669',
    icon: '◉',
    category: 'financial',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Get Balance', value: 'getBalance' },
          { label: 'Send SOL', value: 'sendSol' },
          { label: 'Send Token', value: 'sendToken' },
          { label: 'Check Token Balance', value: 'checkTokenBalance' },
          { label: 'Get Provider Wallets', value: 'getWallets' },
        ],
        required: true,
        default: 'getBalance',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      { key: 'toAddress', label: 'Recipient Address', type: 'text', placeholder: 'Wallet address' },
      { key: 'amount', label: 'Amount', type: 'number', placeholder: '0.1' },
      { key: 'tokenMint', label: 'Token Mint Address', type: 'text', placeholder: 'SPL token mint' },
    ],
  },
  escrow: {
    type: 'escrow',
    label: 'Escrow',
    description: 'Lock funds, release on condition, multi-party escrow',
    color: '#fb923c',
    bgColor: '#1f0a00',
    borderColor: '#ea580c',
    icon: '⊞',
    category: 'financial',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Create Escrow', value: 'create' },
          { label: 'Release Funds', value: 'release' },
          { label: 'Return Funds', value: 'return' },
          { label: 'Get Escrow Status', value: 'status' },
        ],
        required: true,
        default: 'create',
      },
      { key: 'payerAvatarId', label: 'Payer Avatar ID', type: 'text', placeholder: '{{trigger.buyerAvatarId}}' },
      { key: 'payeeAvatarId', label: 'Payee Avatar ID', type: 'text', placeholder: '{{trigger.sellerAvatarId}}' },
      { key: 'amount', label: 'Amount (SOL)', type: 'number', placeholder: '1.0' },
      { key: 'escrowId', label: 'Escrow ID', type: 'text', placeholder: '{{step1.escrowId}}' },
      { key: 'releaseCondition', label: 'Release Condition', type: 'text', placeholder: 'quest_complete' },
    ],
  },
  treasury: {
    type: 'treasury',
    label: 'Treasury',
    description: 'Budget allocation and multi-wallet coordination',
    color: '#f472b6',
    bgColor: '#1f001a',
    borderColor: '#db2777',
    icon: '⬡',
    category: 'financial',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Calculate Distribution', value: 'calculate' },
          { label: 'Execute Distribution', value: 'execute' },
          { label: 'Get Budget', value: 'getBudget' },
        ],
        required: true,
        default: 'calculate',
      },
      { key: 'totalAmount', label: 'Total Amount', type: 'number', placeholder: '10.0' },
      { key: 'recipients', label: 'Recipients (JSON)', type: 'textarea', placeholder: '[{"wallet":"...","share":0.7}]' },
    ],
  },
  x402: {
    type: 'x402',
    label: 'X402',
    description: 'Distribute revenue to token/NFT holders',
    color: '#facc15',
    bgColor: '#1a1200',
    borderColor: '#ca8a04',
    icon: '⊛',
    category: 'financial',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Get Eligible Recipients', value: 'getRecipients' },
          { label: 'Execute Drip', value: 'drip' },
        ],
        required: true,
        default: 'getRecipients',
      },
      { key: 'poolId', label: 'Pool ID', type: 'text', placeholder: 'Revenue pool identifier' },
      { key: 'amount', label: 'Drip Amount (SOL)', type: 'number', placeholder: '0.5' },
      { key: 'minBalance', label: 'Min Token Balance', type: 'number', placeholder: '10000' },
    ],
  },
  bridge: {
    type: 'bridge',
    label: 'Bridge',
    description: 'Cross-chain asset bridge with proof holon',
    color: '#38bdf8',
    bgColor: '#001a2f',
    borderColor: '#0284c7',
    icon: '⇌',
    category: 'financial',
    inputs: [
      {
        key: 'fromChain',
        label: 'From Chain',
        type: 'select',
        options: [
          { label: 'Ethereum', value: 'EthereumOASIS' },
          { label: 'Solana', value: 'SolanaOASIS' },
          { label: 'Polygon', value: 'PolygonOASIS' },
        ],
        required: true,
        default: 'EthereumOASIS',
      },
      {
        key: 'toChain',
        label: 'To Chain',
        type: 'select',
        options: [
          { label: 'Ethereum', value: 'EthereumOASIS' },
          { label: 'Solana', value: 'SolanaOASIS' },
          { label: 'Polygon', value: 'PolygonOASIS' },
        ],
        required: true,
        default: 'SolanaOASIS',
      },
      { key: 'amount', label: 'Amount', type: 'number', placeholder: '1.0' },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
    ],
  },

  // ── Identity & Reputation ───────────────────────────────────────────────────
  avatar: {
    type: 'avatar',
    label: 'Avatar',
    description: 'Load avatar, check karma, verify KYC, get cross-game identity',
    color: '#67e8f9',
    bgColor: '#0c1a2e',
    borderColor: '#0e7490',
    icon: '👤',
    category: 'identity',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Load Avatar', value: 'load' },
          { label: 'Update Avatar', value: 'update' },
          { label: 'Get Karma', value: 'getKarma' },
          { label: 'Verify KYC Holon', value: 'verifyKyc' },
          { label: 'Get My Quests', value: 'getMyQuests' },
        ],
        required: true,
        default: 'load',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
    ],
  },
  karma: {
    type: 'karma',
    label: 'Karma',
    description: 'Add or remove karma points, read avatar reputation',
    color: '#e879f9',
    bgColor: '#1a0020',
    borderColor: '#a21caf',
    icon: '☯',
    category: 'identity',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Add Karma', value: 'add' },
          { label: 'Remove Karma', value: 'remove' },
          { label: 'Get Karma', value: 'get' },
          { label: 'Get Karma History', value: 'history' },
        ],
        required: true,
        default: 'add',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      {
        key: 'karmaType',
        label: 'Karma Type',
        type: 'select',
        options: [
          { label: 'Level Up', value: 'LevelUp' },
          { label: 'Help Other Person', value: 'HelpOtherPerson' },
          { label: 'Be A Hero', value: 'BeAHero' },
          { label: 'Helping Animals', value: 'HelpingAnimals' },
          { label: 'Helping The Environment', value: 'HelpingTheEnvironment' },
          { label: 'Self Help Improvement', value: 'SelfHelpImprovement' },
          { label: 'Other', value: 'Other' },
        ],
        default: 'LevelUp',
      },
      {
        key: 'karmaSource',
        label: 'Source',
        type: 'select',
        options: [
          { label: 'Game', value: 'Game' },
          { label: 'App', value: 'App' },
          { label: 'dApp', value: 'dApp' },
          { label: 'Website', value: 'Website' },
        ],
        default: 'Game',
      },
    ],
  },

  // ── Game & Quests (STAR API) ─────────────────────────────────────────────────
  quest: {
    type: 'quest',
    label: 'Quest',
    description: 'STAR API: create, start, complete quests and objectives. POST /api/quests/complete to award karma + NFT via registry.',
    color: '#a3e635',
    bgColor: '#0d1a00',
    borderColor: '#65a30d',
    icon: '⊕',
    category: 'game',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Complete Objective (POST /api/quests/complete)', value: 'completeObjective' },
          { label: 'Start Quest (POST /api/quests/start)', value: 'start' },
          { label: 'Create Quest (POST /api/quests)', value: 'create' },
          { label: 'Get Quest Status (GET /api/quests/{id})', value: 'status' },
          { label: 'List Quests for Avatar (GET /api/quests)', value: 'listForAvatar' },
          { label: 'Get Quest Objectives (GET /api/quests/{id}/objectives)', value: 'getObjectives' },
          { label: 'Get Quest Rewards (GET /api/quests/{id}/rewards)', value: 'getRewards' },
          { label: 'Register Quest in Registry', value: 'register' },
          { label: 'Complete Quest (POST /api/quests/complete)', value: 'complete' },
        ],
        required: true,
        default: 'completeObjective',
      },
      { key: 'questId', label: 'Quest ID', type: 'text', placeholder: '{{trigger.questId}} or quest_123' },
      { key: 'gameId', label: 'Game ID', type: 'text', placeholder: 'my-game, isocity, ar-world' },
      { key: 'objectiveKey', label: 'Objective Key', type: 'text', placeholder: 'boss-defeated, level-complete, population_100' },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      { key: 'questName', label: 'Quest Name', type: 'text', placeholder: 'The Lost Relic (for create)' },
      {
        key: 'questType',
        label: 'Quest Type',
        type: 'select',
        options: [
          { label: 'Main', value: 'Main' },
          { label: 'Side', value: 'Side' },
          { label: 'Daily', value: 'Daily' },
          { label: 'Weekly', value: 'Weekly' },
          { label: 'Event', value: 'Event' },
        ],
        default: 'Side',
      },
      {
        key: 'difficulty',
        label: 'Difficulty',
        type: 'select',
        options: [
          { label: 'Easy', value: 'Easy' },
          { label: 'Medium', value: 'Medium' },
          { label: 'Hard', value: 'Hard' },
          { label: 'Legendary', value: 'Legendary' },
        ],
        default: 'Medium',
      },
      { key: 'karmaReward', label: 'Karma Reward', type: 'number', placeholder: '100' },
      { key: 'xpReward', label: 'XP Reward', type: 'number', placeholder: '50' },
      { key: 'physicalReward', label: 'Has Physical Reward (Q2P)', type: 'boolean', default: false },
    ],
  },
  mission: {
    type: 'mission',
    label: 'Mission',
    description: 'STAR API: create multi-quest missions, complete missions, get leaderboards. GET/POST /api/missions',
    color: '#f59e0b',
    bgColor: '#1a0e00',
    borderColor: '#b45309',
    icon: '🎯',
    category: 'game',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Complete Mission (POST /api/missions/{id}/complete)', value: 'complete' },
          { label: 'Create Mission (POST /api/missions)', value: 'create' },
          { label: 'Get Missions for Avatar (GET /api/missions/load-all-for-avatar)', value: 'getForAvatar' },
          { label: 'Get Mission Leaderboard (GET /api/missions/{id}/leaderboard)', value: 'leaderboard' },
          { label: 'Get Mission Stats (GET /api/missions/stats)', value: 'stats' },
          { label: 'Get Mission (GET /api/missions/{id})', value: 'get' },
        ],
        required: true,
        default: 'complete',
      },
      { key: 'missionId', label: 'Mission ID', type: 'text', placeholder: '{{trigger.missionId}} or UUID' },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      { key: 'missionName', label: 'Mission Name', type: 'text', placeholder: 'The Grand Adventure (for create)' },
      {
        key: 'missionType',
        label: 'Mission Type',
        type: 'select',
        options: [
          { label: 'Quest Chain', value: 'Quest' },
          { label: 'Challenge', value: 'Challenge' },
          { label: 'Task', value: 'Task' },
          { label: 'Achievement', value: 'Achievement' },
        ],
        default: 'Quest',
      },
      { key: 'linkedQuestIds', label: 'Linked Quest IDs (JSON)', type: 'textarea', placeholder: '["quest_1","quest_2","quest_3"]' },
      { key: 'karmaReward', label: 'Karma Reward', type: 'number', placeholder: '500' },
    ],
  },
  geonfft: {
    type: 'geonfft',
    label: 'GeoNFT',
    description: 'STAR API: mint & place NFTs at GPS coordinates, check & collect at location. POST /api/nft/mint-and-place-geo-nft',
    color: '#84cc16',
    bgColor: '#0d1800',
    borderColor: '#4d7c0f',
    icon: '📍',
    category: 'game',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Mint & Place at GPS (POST /api/nft/mint-and-place-geo-nft)', value: 'mintAndPlace' },
          { label: 'Get GeoNFTs for Avatar (GET /api/nft/load-all-geo-nfts-for-avatar)', value: 'getForAvatar' },
          { label: 'Check Nearby (GET /api/map/nearby)', value: 'nearby' },
          { label: 'Visit Location (POST /api/map/visit/{locationId})', value: 'visit' },
          { label: 'Search Locations (POST /api/map/search)', value: 'search' },
        ],
        required: true,
        default: 'mintAndPlace',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      { key: 'title', label: 'GeoNFT Title', type: 'text', placeholder: 'Ancient Relic at Tower Bridge' },
      { key: 'description', label: 'Description', type: 'text', placeholder: 'A rare artifact hidden near...' },
      { key: 'imageUrl', label: 'Image URL', type: 'text', placeholder: 'https://... or {{braid.imageUrl}}' },
      { key: 'lat', label: 'Latitude', type: 'text', placeholder: '51.5079' },
      { key: 'lng', label: 'Longitude', type: 'text', placeholder: '-0.0877' },
      { key: 'radius', label: 'Claim Radius (metres)', type: 'number', placeholder: '50', default: 50 },
      { key: 'locationId', label: 'Location ID', type: 'text', placeholder: '{{trigger.locationId}} (for visit)' },
      {
        key: 'cluster',
        label: 'Cluster',
        type: 'select',
        options: [
          { label: 'Devnet (testing)', value: 'devnet' },
          { label: 'Mainnet', value: 'mainnet-beta' },
        ],
        default: 'devnet',
      },
    ],
  },
  egg: {
    type: 'egg',
    label: 'Egg',
    description: 'STAR API: discover and hatch eggs, get egg quests. GET /api/eggs/get-current-egg-quests',
    color: '#fb923c',
    bgColor: '#1f0800',
    borderColor: '#c2410c',
    icon: '🥚',
    category: 'game',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Get Current Egg Quests (GET /api/eggs/get-current-egg-quests)', value: 'getEggQuests' },
          { label: 'Discover Egg (POST /api/eggs/discover)', value: 'discover' },
          { label: 'Hatch Egg (POST /api/eggs/hatch/{eggId})', value: 'hatch' },
          { label: 'Get All Eggs (GET /api/eggs/get-all-eggs)', value: 'getAll' },
        ],
        required: true,
        default: 'discover',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      { key: 'eggId', label: 'Egg ID', type: 'text', placeholder: '{{trigger.eggId}} (for hatch)' },
      { key: 'locationId', label: 'Location ID', type: 'text', placeholder: '{{trigger.locationId}} (for discover)' },
      { key: 'lat', label: 'Latitude', type: 'text', placeholder: '{{trigger.lat}}' },
      { key: 'lng', label: 'Longitude', type: 'text', placeholder: '{{trigger.lng}}' },
    ],
  },
  leaderboard: {
    type: 'leaderboard',
    label: 'Leaderboard',
    description: 'STAR API: get rankings, my rank, leagues, tournaments. GET /api/competition/leaderboard',
    color: '#fbbf24',
    bgColor: '#1a1000',
    borderColor: '#92400e',
    icon: '🏆',
    category: 'game',
    inputs: [
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Get Leaderboard (GET /api/competition/leaderboard/{type}/{season})', value: 'getLeaderboard' },
          { label: 'Get My Rank (GET /api/competition/my-rank)', value: 'getMyRank' },
          { label: 'Get Leagues (GET /api/competition/leagues)', value: 'getLeagues' },
          { label: 'Get Tournaments (GET /api/competition/tournaments)', value: 'getTournaments' },
        ],
        required: true,
        default: 'getLeaderboard',
      },
      { key: 'avatarId', label: 'Avatar ID', type: 'text', placeholder: '{{trigger.avatarId}}' },
      {
        key: 'leaderboardType',
        label: 'Leaderboard Type',
        type: 'select',
        options: [
          { label: 'Global', value: 'global' },
          { label: 'Game-specific', value: 'game' },
          { label: 'Weekly', value: 'weekly' },
          { label: 'Monthly', value: 'monthly' },
        ],
        default: 'global',
      },
      { key: 'season', label: 'Season', type: 'text', placeholder: 'current (or season ID)' },
      { key: 'gameId', label: 'Game ID (for game type)', type: 'text', placeholder: 'my-game' },
      { key: 'limit', label: 'Result Limit', type: 'number', placeholder: '10', default: 10 },
    ],
  },

  // ── Logic & Control ─────────────────────────────────────────────────────────
  condition: {
    type: 'condition',
    label: 'Condition',
    description: 'Branch logic — if/else based on previous step output',
    color: '#f87171',
    bgColor: '#1f0000',
    borderColor: '#dc2626',
    icon: '⟨⟩',
    category: 'logic',
    inputs: [
      { key: 'expression', label: 'Condition Expression', type: 'text', placeholder: '{{quest.completed}} == true', required: true },
      { key: 'trueLabel', label: 'True Branch Label', type: 'text', placeholder: 'Quest complete', default: 'Yes' },
      { key: 'falseLabel', label: 'False Branch Label', type: 'text', placeholder: 'Not yet', default: 'No' },
    ],
  },
  delay: {
    type: 'delay',
    label: 'Delay',
    description: 'Wait before the next step',
    color: '#64748b',
    bgColor: '#0f1218',
    borderColor: '#475569',
    icon: '⏱',
    category: 'logic',
    inputs: [
      { key: 'seconds', label: 'Delay (seconds)', type: 'number', placeholder: '60', required: true, default: 5 },
      { key: 'until', label: 'Or wait until (ISO datetime)', type: 'text', placeholder: '2026-03-01T12:00:00Z' },
    ],
  },
}

  // ── Named Integrations ──────────────────────────────────────────────────────
  slack: {
    type: 'slack',
    label: 'Slack',
    description: 'Send messages, alerts, and notifications to Slack channels or DMs',
    color: '#e8f5e9',
    bgColor: '#1a1f1a',
    borderColor: '#36c037',
    icon: '#',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'Incoming Webhook URL (paste from Slack)', value: 'api_key' },
          { label: 'OAuth App (coming soon)', value: 'oauth_stub' },
        ],
        default: 'api_key',
      },
      { key: 'webhookUrl', label: 'Slack Webhook URL', type: 'text', placeholder: 'https://hooks.slack.com/services/T.../B.../...', required: true },
      { key: 'channel', label: 'Channel (optional override)', type: 'text', placeholder: '#customer-success' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Post message', value: 'post_message' },
          { label: 'Post deviation alert', value: 'post_deviation' },
          { label: 'Post run completion', value: 'post_completion' },
        ],
        default: 'post_message',
      },
      { key: 'messageTemplate', label: 'Message Template', type: 'textarea', placeholder: 'SOP step {{step.name}} completed by {{avatar.name}} at {{completedAt}}' },
    ],
  },
  email: {
    type: 'email',
    label: 'Email',
    description: 'Send emails via SendGrid, SES, or SMTP — step assignments, overdue reminders, summaries',
    color: '#fef3c7',
    bgColor: '#1a1600',
    borderColor: '#d97706',
    icon: '@',
    category: 'integration',
    inputs: [
      {
        key: 'provider',
        label: 'Provider',
        type: 'select',
        options: [
          { label: 'SendGrid', value: 'sendgrid' },
          { label: 'Amazon SES', value: 'ses' },
          { label: 'SMTP', value: 'smtp' },
          { label: 'Mailgun', value: 'mailgun' },
        ],
        default: 'sendgrid',
      },
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'SG.xxxxxxxxxxxxxxxx (SendGrid) or key-xxx (Mailgun)' },
      { key: 'fromAddress', label: 'From Address', type: 'text', placeholder: 'sop@yourcompany.com' },
      { key: 'toAddress', label: 'To Address', type: 'text', placeholder: '{{avatar.email}} or fixed@email.com' },
      { key: 'subject', label: 'Subject', type: 'text', placeholder: 'Action required: {{step.name}} — {{sop.name}}' },
      { key: 'bodyTemplate', label: 'Body Template (HTML)', type: 'textarea', placeholder: '<p>Hi {{avatar.firstName}},</p><p>Step <strong>{{step.name}}</strong> is assigned to you...</p>' },
    ],
  },
  salesforce: {
    type: 'salesforce',
    label: 'Salesforce',
    description: 'Trigger SOPs from deal stage changes; update opportunities, contacts, and activities on step completion',
    color: '#dbeafe',
    bgColor: '#001a3d',
    borderColor: '#1e40af',
    icon: 'SF',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'Connected App (OAuth2 — coming soon)', value: 'oauth_stub' },
          { label: 'Username + Password + Security Token', value: 'api_key' },
        ],
        default: 'api_key',
      },
      { key: 'instanceUrl', label: 'Instance URL', type: 'text', placeholder: 'https://mycompany.my.salesforce.com' },
      { key: 'accessToken', label: 'Access Token / Session Token', type: 'text', placeholder: 'Paste token from Salesforce Setup > API' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Update Opportunity Stage', value: 'update_opportunity' },
          { label: 'Create Task / Activity', value: 'create_task' },
          { label: 'Update Contact', value: 'update_contact' },
          { label: 'Create Custom Object Record', value: 'create_record' },
          { label: 'Query Records (SOQL)', value: 'query' },
        ],
        default: 'update_opportunity',
      },
      { key: 'objectId', label: 'Record ID', type: 'text', placeholder: '{{trigger.salesforceOpportunityId}}' },
      { key: 'fieldsJson', label: 'Fields to Update (JSON)', type: 'textarea', placeholder: '{"StageName": "Customer", "CloseDate": "{{run.completedAt}}"}' },
    ],
  },
  hubspot: {
    type: 'hubspot',
    label: 'HubSpot',
    description: 'Trigger SOPs from HubSpot deal stage; update deals, contacts, and log timeline events',
    color: '#fde8d8',
    bgColor: '#1f0d00',
    borderColor: '#f97316',
    icon: 'HS',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'Private App Token (recommended)', value: 'api_key' },
          { label: 'OAuth2 (coming soon)', value: 'oauth_stub' },
        ],
        default: 'api_key',
      },
      { key: 'apiKey', label: 'Private App Token', type: 'text', placeholder: 'pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Update Deal Stage', value: 'update_deal' },
          { label: 'Create Note / Timeline Event', value: 'create_note' },
          { label: 'Update Contact Property', value: 'update_contact' },
          { label: 'Create Task', value: 'create_task' },
          { label: 'Get Contact by Email', value: 'get_contact' },
        ],
        default: 'update_deal',
      },
      { key: 'objectId', label: 'Object ID', type: 'text', placeholder: '{{trigger.hubspotDealId}}' },
      { key: 'fieldsJson', label: 'Properties (JSON)', type: 'textarea', placeholder: '{"dealstage": "closedwon", "hs_deal_stage_probability": "1.0"}' },
    ],
  },
  zendesk: {
    type: 'zendesk',
    label: 'Zendesk',
    description: 'Create tickets when SOPs start; add comments and resolve tickets as steps complete',
    color: '#ede9fe',
    bgColor: '#0d001f',
    borderColor: '#7c3aed',
    icon: 'ZD',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'API Token (email/token)', value: 'api_key' },
          { label: 'OAuth2 (coming soon)', value: 'oauth_stub' },
        ],
        default: 'api_key',
      },
      { key: 'subdomain', label: 'Subdomain', type: 'text', placeholder: 'yourcompany (from yourcompany.zendesk.com)' },
      { key: 'email', label: 'Agent Email', type: 'text', placeholder: 'agent@yourcompany.com' },
      { key: 'apiToken', label: 'API Token', type: 'text', placeholder: 'From Zendesk Admin > Channels > API' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Create Ticket', value: 'create_ticket' },
          { label: 'Add Comment to Ticket', value: 'add_comment' },
          { label: 'Update Ticket Status', value: 'update_status' },
          { label: 'Resolve Ticket', value: 'resolve_ticket' },
          { label: 'Get Ticket', value: 'get_ticket' },
        ],
        default: 'create_ticket',
      },
      { key: 'ticketId', label: 'Ticket ID', type: 'text', placeholder: '{{run.externalContextId}} (for update/comment)' },
      { key: 'subject', label: 'Subject', type: 'text', placeholder: 'SOP: {{sop.name}} — {{customer.name}}' },
      { key: 'bodyTemplate', label: 'Body / Comment', type: 'textarea', placeholder: 'SOP run {{run.id}} started. Step: {{step.name}}' },
    ],
  },
  docusign: {
    type: 'docusign',
    label: 'DocuSign',
    description: 'Send signature requests for sign-off steps; wait for completion before advancing the SOP',
    color: '#dcfce7',
    bgColor: '#001a0a',
    borderColor: '#16a34a',
    icon: 'DS',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'Integration Key + Access Token', value: 'api_key' },
          { label: 'JWT Grant (service account — coming soon)', value: 'oauth_stub' },
        ],
        default: 'api_key',
      },
      { key: 'accountId', label: 'DocuSign Account ID', type: 'text', placeholder: 'From DocuSign Admin > API & Keys' },
      { key: 'accessToken', label: 'Access Token', type: 'text', placeholder: 'OAuth access token' },
      { key: 'basePath', label: 'Base Path', type: 'select', options: [{ label: 'Production', value: 'https://na4.docusign.net/restapi' }, { label: 'Sandbox (demo)', value: 'https://demo.docusign.net/restapi' }], default: 'https://demo.docusign.net/restapi' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Send Envelope for Signature', value: 'send_envelope' },
          { label: 'Get Envelope Status', value: 'get_status' },
          { label: 'Download Signed Document', value: 'download_doc' },
        ],
        default: 'send_envelope',
      },
      { key: 'signerEmail', label: 'Signer Email', type: 'text', placeholder: '{{avatar.email}} or {{customer.email}}' },
      { key: 'signerName', label: 'Signer Name', type: 'text', placeholder: '{{avatar.fullName}}' },
      { key: 'documentUrl', label: 'Document URL (PDF)', type: 'text', placeholder: 'https://... or {{step.output.documentUrl}}' },
      { key: 'emailSubject', label: 'Email Subject', type: 'text', placeholder: 'Please sign: {{sop.name}} go-live confirmation' },
    ],
  },
  google_calendar: {
    type: 'google_calendar',
    label: 'Google Calendar',
    description: 'Create calendar events and meeting invites as part of SOP steps — kickoffs, check-ins, deadlines',
    color: '#fce7f3',
    bgColor: '#1f001a',
    borderColor: '#db2777',
    icon: 'GC',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'Service Account JSON Key', value: 'api_key' },
          { label: 'OAuth2 User (coming soon)', value: 'oauth_stub' },
        ],
        default: 'api_key',
      },
      { key: 'serviceAccountJson', label: 'Service Account Key (JSON)', type: 'textarea', placeholder: 'Paste contents of downloaded service-account.json key file' },
      { key: 'calendarId', label: 'Calendar ID', type: 'text', placeholder: 'primary or custom@yourcompany.com' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Create Event', value: 'create_event' },
          { label: 'Update Event', value: 'update_event' },
          { label: 'Delete Event', value: 'delete_event' },
          { label: 'Get Event', value: 'get_event' },
        ],
        default: 'create_event',
      },
      { key: 'title', label: 'Event Title', type: 'text', placeholder: 'Kickoff: {{customer.name}} — {{sop.name}}' },
      { key: 'startTime', label: 'Start Time (ISO)', type: 'text', placeholder: '{{step.output.scheduledAt}} or 2026-04-01T10:00:00Z' },
      { key: 'durationMinutes', label: 'Duration (minutes)', type: 'number', placeholder: '60' },
      { key: 'attendeesJson', label: 'Attendees (JSON array of emails)', type: 'textarea', placeholder: '["{{avatar.email}}", "{{customer.email}}"]' },
      { key: 'description', label: 'Event Description', type: 'textarea', placeholder: 'SOP: {{sop.name}}\nRun ID: {{run.id}}' },
    ],
  },
  jira: {
    type: 'jira',
    label: 'Jira',
    description: 'Create issues and epics when SOPs start; transition and resolve issues as steps complete',
    color: '#dbeafe',
    bgColor: '#00081a',
    borderColor: '#2563eb',
    icon: 'Ji',
    category: 'integration',
    inputs: [
      {
        key: 'authMode',
        label: 'Auth Mode',
        type: 'select',
        options: [
          { label: 'API Token (email + token)', value: 'api_key' },
          { label: 'OAuth2 (coming soon)', value: 'oauth_stub' },
        ],
        default: 'api_key',
      },
      { key: 'instanceUrl', label: 'Jira Instance URL', type: 'text', placeholder: 'https://yourcompany.atlassian.net' },
      { key: 'email', label: 'Email', type: 'text', placeholder: 'you@yourcompany.com' },
      { key: 'apiToken', label: 'API Token', type: 'text', placeholder: 'From Atlassian Account Settings > Security > API tokens' },
      { key: 'projectKey', label: 'Project Key', type: 'text', placeholder: 'CS, OPS, ENG' },
      {
        key: 'action',
        label: 'Action',
        type: 'select',
        options: [
          { label: 'Create Issue', value: 'create_issue' },
          { label: 'Transition Issue', value: 'transition_issue' },
          { label: 'Add Comment', value: 'add_comment' },
          { label: 'Update Issue', value: 'update_issue' },
          { label: 'Get Issue', value: 'get_issue' },
        ],
        default: 'create_issue',
      },
      { key: 'issueKey', label: 'Issue Key', type: 'text', placeholder: 'CS-123 (for transition/comment/update)' },
      { key: 'summary', label: 'Summary', type: 'text', placeholder: 'SOP: {{sop.name}} — {{customer.name}}' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Automated from SOP run {{run.id}}\nStep: {{step.name}}' },
      { key: 'issueType', label: 'Issue Type', type: 'select', options: [{ label: 'Task', value: 'Task' }, { label: 'Story', value: 'Story' }, { label: 'Epic', value: 'Epic' }, { label: 'Bug', value: 'Bug' }], default: 'Task' },
      { key: 'transitionId', label: 'Transition ID', type: 'text', placeholder: '31 (for transition — get from /rest/api/3/issue/{key}/transitions)' },
    ],
  },
  zapier: {
    type: 'zapier',
    label: 'Zapier',
    description: 'Trigger any of 7,000+ apps through a Zapier webhook — the universal integration escape hatch',
    color: '#fef9c3',
    bgColor: '#1a1800',
    borderColor: '#ca8a04',
    icon: 'Zp',
    category: 'integration',
    inputs: [
      { key: 'webhookUrl', label: 'Zapier Webhook URL (Catch Hook)', type: 'text', placeholder: 'https://hooks.zapier.com/hooks/catch/xxxxxxx/xxxxxxx/', required: true },
      {
        key: 'triggerEvent',
        label: 'Trigger Event',
        type: 'select',
        options: [
          { label: 'SOP Step Completed', value: 'step_completed' },
          { label: 'SOP Run Started', value: 'run_started' },
          { label: 'SOP Run Completed', value: 'run_completed' },
          { label: 'Deviation Detected', value: 'deviation_detected' },
          { label: 'Custom', value: 'custom' },
        ],
        default: 'step_completed',
      },
      { key: 'payloadJson', label: 'Custom Payload (JSON)', type: 'textarea', placeholder: '{"sopId": "{{sop.id}}", "stepName": "{{step.name}}", "avatarId": "{{avatar.id}}", "completedAt": "{{completedAt}}"}' },
      { key: 'note', label: 'Note (for your reference)', type: 'text', placeholder: 'e.g. Updates Airtable row when step 3 completes' },
    ],
  },

  // ── SOP-Specific Nodes ───────────────────────────────────────────────────────
  sop_step: {
    type: 'sop_step',
    label: 'SOP Step',
    description: 'Define a single SOP instruction — role, timeout, evidence requirement, AI prompt, and sign-off rules',
    color: '#fed7aa',
    bgColor: '#1f0a00',
    borderColor: '#ea580c',
    icon: '▶',
    category: 'sop',
    inputs: [
      { key: 'stepName', label: 'Step Name', type: 'text', placeholder: 'Send welcome email', required: true },
      { key: 'description', label: 'Instruction Text', type: 'textarea', placeholder: 'Full instruction shown to the person executing this step...' },
      { key: 'assignedRole', label: 'Assigned Role', type: 'text', placeholder: 'CustomerSuccessManager, SolutionsEngineer, Admin...' },
      { key: 'stepNumber', label: 'Step Number', type: 'number', placeholder: '1 (equal numbers run in parallel)' },
      { key: 'timeoutMinutes', label: 'Timeout (minutes)', type: 'number', placeholder: '60 (deviation flagged if exceeded)' },
      {
        key: 'onFailure',
        label: 'On Failure',
        type: 'select',
        options: [
          { label: 'Abort SOP run', value: 'abort' },
          { label: 'Skip this step', value: 'skip' },
          { label: 'Retry (auto)', value: 'retry' },
          { label: 'Escalate to manager', value: 'escalate' },
        ],
        default: 'abort',
      },
      { key: 'requiresSignOff', label: 'Requires Avatar Sign-Off', type: 'boolean', default: false },
      { key: 'requiresEvidence', label: 'Requires Evidence Upload', type: 'boolean', default: false },
      { key: 'aiPrompt', label: 'AI Guidance Prompt (BRAID)', type: 'textarea', placeholder: 'Draft a personalised welcome email using {input.customerName} and {input.industry}. Return subject and body.' },
      { key: 'inputSchema', label: 'Expected Inputs (JSON schema)', type: 'textarea', placeholder: '{"customerName": "string", "industry": "string"}' },
      { key: 'outputSchema', label: 'Expected Outputs (JSON schema)', type: 'textarea', placeholder: '{"emailSentAt": "datetime", "calendarEventId": "string"}' },
    ],
  },
  sop_decision: {
    type: 'sop_decision',
    label: 'SOP Decision',
    description: 'Branch the SOP based on a field value — numeric threshold, string match, boolean flag, or AI evaluation',
    color: '#fca5a5',
    bgColor: '#1f0000',
    borderColor: '#dc2626',
    icon: '⋈',
    category: 'sop',
    inputs: [
      { key: 'decisionName', label: 'Decision Name', type: 'text', placeholder: 'Complexity Score Branch', required: true },
      { key: 'conditionField', label: 'Field to Evaluate', type: 'text', placeholder: 'IntegrationComplexityScore (output from previous step)', required: true },
      {
        key: 'conditionType',
        label: 'Condition Type',
        type: 'select',
        options: [
          { label: 'Numeric threshold (e.g. >=3)', value: 'numeric_threshold' },
          { label: 'String equals', value: 'string_equals' },
          { label: 'Boolean flag', value: 'bool_flag' },
          { label: 'AI evaluated (BRAID interprets)', value: 'ai_evaluated' },
        ],
        default: 'numeric_threshold',
        required: true,
      },
      { key: 'branchesJson', label: 'Branches (JSON)', type: 'textarea', placeholder: '[{"name":"ENTERPRISE PATH","value":">=3","firstStepId":""},{"name":"SIMPLE PATH","value":"<3","firstStepId":""}]' },
      { key: 'aiEvalPrompt', label: 'AI Eval Prompt (if ai_evaluated)', type: 'textarea', placeholder: 'Given the field value {conditionField}, determine which path to take: ENTERPRISE or SIMPLE. Return exactly one path name.' },
    ],
  },
  sop_signoff: {
    type: 'sop_signoff',
    label: 'SOP Sign-Off',
    description: 'Request an Avatar wallet signature or external DocuSign before the SOP can advance',
    color: '#d1fae5',
    bgColor: '#001f14',
    borderColor: '#059669',
    icon: '✍',
    category: 'sop',
    inputs: [
      { key: 'stepName', label: 'Sign-Off Name', type: 'text', placeholder: 'Customer go-live approval', required: true },
      { key: 'assignedRole', label: 'Who Must Sign', type: 'text', placeholder: 'CustomerAdmin, ExecutiveDirector, LPRepresentative' },
      {
        key: 'signoffType',
        label: 'Sign-Off Type',
        type: 'select',
        options: [
          { label: 'OASIS Avatar Wallet Signature', value: 'avatar_wallet' },
          { label: 'DocuSign Envelope', value: 'external_docusign' },
          { label: 'Acknowledgement Checkbox (no crypto)', value: 'checkbox' },
        ],
        default: 'avatar_wallet',
        required: true,
      },
      { key: 'signerAvatarId', label: 'Signer Avatar ID (if known)', type: 'text', placeholder: '{{trigger.customerAvatarId}}' },
      { key: 'signerEmail', label: 'Signer Email (for DocuSign)', type: 'text', placeholder: '{{customer.email}}' },
      { key: 'documentUrl', label: 'Document URL (for DocuSign)', type: 'text', placeholder: '{{step.output.documentUrl}}' },
      { key: 'confirmationMessage', label: 'Confirmation Message Shown to Signer', type: 'textarea', placeholder: 'By signing, you confirm that the onboarding is complete and you are ready to go live.' },
    ],
  },
  sop_ai_guide: {
    type: 'sop_ai_guide',
    label: 'AI Guide (BRAID)',
    description: 'Inject BRAID AI guidance at a specific SOP step — contextual advice, document drafting, analysis, or deviation detection',
    color: '#f3e8ff',
    bgColor: '#1a0033',
    borderColor: '#9333ea',
    icon: '◈',
    category: 'sop',
    inputs: [
      { key: 'guidanceName', label: 'Guidance Name', type: 'text', placeholder: 'Discovery call summary + complexity score', required: true },
      { key: 'braidPrompt', label: 'BRAID Prompt', type: 'textarea', placeholder: 'Using the discovery notes {input.discoveryNotes}, score the integration complexity 1-5 and explain the main technical risks. Return JSON: {"score": number, "reasoning": string, "risks": string[]}', required: true },
      {
        key: 'model',
        label: 'LLM Model',
        type: 'select',
        options: [
          { label: 'Anthropic Claude (preferred)', value: 'anthropic' },
          { label: 'OpenAI GPT-4', value: 'openai' },
        ],
        default: 'anthropic',
      },
      { key: 'contextHolonId', label: 'Context Holon ID (optional)', type: 'text', placeholder: '{{sop.workflowHolonId}} — BRAID reads this holon for additional context' },
      { key: 'outputField', label: 'Output Field Name', type: 'text', placeholder: 'complexityAnalysis (accessible as {{sop_ai_guide.complexityAnalysis}} downstream)' },
      { key: 'saveAsHolon', label: 'Save AI Output as Holon', type: 'boolean', default: false },
    ],
  },
}

export const CATEGORIES = {
  trigger:     { label: 'Triggers',             color: '#818cf8' },
  game:        { label: 'Game & Quests',         color: '#a3e635' },
  identity:    { label: 'Identity & Avatar',     color: '#67e8f9' },
  ai:          { label: 'AI & Agents',           color: '#a78bfa' },
  data:        { label: 'Data & Storage',        color: '#94a3b8' },
  financial:   { label: 'Financial',             color: '#34d399' },
  logic:       { label: 'Logic & Control',       color: '#f87171' },
  integration: { label: 'Integrations',          color: '#60a5fa' },
  sop:         { label: 'SOP Nodes',             color: '#f97316' },
}
